#!/usr/bin/env python3
# Copyright 2019 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from __future__ import print_function

import sys

import flimflam

if len(sys.argv) < 3:
    print('Usage: %s <service-name> <property>' % (sys.argv[0]))
    sys.exit(1)

(_, name, service_property) = sys.argv

flim = flimflam.FlimFlam()
service = flim.FindElementByNameSubstring('Service', name)
service.ClearProperty(service_property)
