#!/usr/bin/env python3
# Copyright 2018 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from __future__ import print_function

import sys

import dbus
import flimflam

if len(sys.argv) < 3:
    print('Usage: %s <device_claimer> <device_name>' % (sys.argv[0]))
    sys.exit(1)

bus = dbus.SystemBus()
manager = dbus.Interface(bus.get_object('org.chromium.flimflam', '/'),
                         'org.chromium.flimflam.Manager')
print(manager.ReleaseInterface(sys.argv[1], sys.argv[2]))
