#!/usr/bin/env python3
# Copyright 2019 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from __future__ import print_function

import sys

import dbus
import flimflam

flim = flimflam.FlimFlam(dbus.SystemBus())

if len(sys.argv) < 2:
    print('Service order is %s' % flim.GetServiceOrder())
else:
    orders = flim.SetServiceOrder(sys.argv[1])
    print('Service order %s => %s' % orders)
