#!/usr/bin/env python3
# Copyright 2019 The Chromium OS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

from __future__ import print_function

import sys

import dbus
import flimflam

if len(sys.argv) != 2:
    print('Usage: %s <technology>' % (sys.argv[0]))
    sys.exit(1)

flim = flimflam.FlimFlam(dbus.SystemBus())
flim.RequestScan(sys.argv[1])
