// Copyright (c) 2019 Mumba. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import ProtocolBuffers

public enum HandleMethodError: Error {
  case unknownMethod
}

// Helper protocol to let one `ServiceServer` serve multiple gRpc services.
// Implementations for these methods are usually provided by the code generated by our protoc plugin.
public protocol ServiceProvider {
  // The name of the service (including package names) provided by this object, e.g. "echo.Echo".
  var serviceName: String { get }
  
  /// Handle the given method. Needs to be overridden by actual implementations.
  func handleMethod(_ method: String, callId: Int, handler: RpcHandler) throws -> ServerStatus?
}
